models:
  - name: mart__dim_bike_stations
    description: "bike stations with name, latitude and longitude"
    columns:
      - name: station_id
        description: "bike station id, primary key"

      - name: station_name
        description: "The name or label associated with the bike station."

      - name: station_lat
        description: "The latitude coordinate of the bike station's location."

      - name: station_lng
        description: "The longitude coordinate of the bike station's location."

  - name: mart__dim_locations
    description: "taxi locations, used to join with pulocationid and dolocationid,
      taken from dbt seed. Not tested as data is small enough to check visually, as should be the case with use of seeds"
    columns:
      - name: locationid
        description: "primary key, Unique identifier for a location."

      - name: borough
        description: "The district of the location."

      - name: zone
        description: "The zone associated with the location."

      - name: service_zone
        description: "The service zone classification for the location."

  - name: mart__fact_all_bike_trips
    description: "bike trip data normalised with station data stripped out to dim"
    columns:
      - name: started_at_ts
        description: "Timestamp indicating the start time of a bike trip."

      - name: ended_at_ts
        description: "Timestamp indicating the end time of a bike trip."

      - name: duration_min
        description: "Timestamp indicating the end time of a bike trip."

      - name: duration_sec
        description: "Duration of the bike trip in minutes."

      - name: start_station_id
        description: "Identifier for the bike station where the trip started."

      - name: end_station_id
        description: "Identifier for the bike station where the trip ended."

  - name: mart__fact_all_taxi_trips
    description: "all taxi trip data for analysis"
    columns:
      - name: type
        description: "The type of taxi trip"

      - name: pickup_datetime
        description: "Timestamp indicating the pickup time of the taxi trip."

      - name: dropoff_datetime
        description: "dropoff time of the taxi trip."

      - name: duration_min
        description: "Duration of the taxi trip in minutes."

      - name: duration_sec
        description: "Duration of the taxi trip in seconds."

      - name: pulocationid
        description: "Pickup location identifier."

      - name: dolocationid
        description: "Dropoff location identifier."

  - name: mart__fact_all_trips_daily
    description: "all trips including bikes and taxis grouped by day, with averaged trip duration"
    columns:
      - name: type
        description: "The type of trip"

      - name: date
        description: "date on which the trips are aggregated."

      - name: trips
        description: "The total number of trips"

      - name: average_trip_duration_min
        description: "The average duration of trips with mins"

  - name: mart__fact_all_trips
    description: "all trips including bikes and taxis with duration"
    columns:
      - name: type
        description: "The type of trip"

      - name: started_at_ts
        description: "The start of trips"

      - name: ended_at_ts
        description: "The end of trips"

      - name: duration_min
        description: "Duration in mins"

      - name: duration_sec
        description: "Duration in seconds"

  - name: mart__fact_all_trips_daily
    description: "number of trips grouped by pickup borough"
    columns:
      - name: trip_count
        description: "total number of trips."
      - name: borough
        description: "The pickup borough for the aggregated trips."